services:
  wyl:
    image: ghcr.io/aceberg/watchyourlan
    network_mode: "host"      
    restart: unless-stopped
    volumes:
    - ./.dockerdata/wyl:/data/WatchYourLAN
    environment:
      TZ: Europe/Belgrade       
      COLOR: dark
      USE_DB: sqlite 
      HOST: 0.0.0.0
      PORT: "8840"
      TRIM_HIST: "24"
      IFACES: eth0
      LOG_LEVEL: info
      THEME: sand
      TIMEOUT: 120
      SHOUTRRR_URL: ${VAR_WYL_SHOUTRRR_URL}