services:
  jetlog:
    image: pbogre/jetlog
    environment:
      JETLOG_PORT: 80
      SECRET_KEY: ${VAR_SECRET_KEY}
    volumes:
      - .:/data
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - app-net
      
  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    ports:
      - 45876:45876 
    environment:
      PORT: 45876
      KEY: '${VAR_BESZEL_KEY}'
      DOCKER_HOST: "tcp://socket-proxy:2375"
    networks:
      - app-net

  socket-proxy:
    image: wollomatic/socket-proxy:latest
    container_name: socket-proxy
    restart: unless-stopped
    command:
      - '-loglevel=debug'
      - '-allowGET=/v1\..{1,2}/(containers/.*|images/.*|info|version|events.*)'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app-net
      
networks:
  app-net:
    driver: bridge