version: "2"
services:
  smokeping:
    image: lscr.io/linuxserver/smokeping
    container_name: smokeping
    ports:
      - 80:80
    volumes:
      - ./config:/config
      - ./data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade
    hostname: zoidberg
    restart: unless-stopped
    networks:
        - docker-proxynet
        - app-net

  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    user: 65534:65534
    read_only: true
    mem_limit: 256M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    ports:
      - 45876:45876
    environment:
      PORT: 45876
      KEY: '${VAR_BESZEL_KEY}'
      DOCKER_HOST: "tcp://dockerproxy:2375"
    networks:
      - docker-proxynet
      - app-net

  dozzle-agent:
    image: amir20/dozzle:latest
    command: agent
    container_name: dozzle-agent
    restart: unless-stopped
    user: 65534:65534
    read_only: true
    mem_limit: 256M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    volumes:
      - ./tmp:/tmp
    ports:
      - 7007:7007
    environment:
      - PORT=7007
      - BESZEL_HOSTNAME=234-smokeping
      - DOCKER_HOST=tcp://dockerproxy:2375
      - HOME=/tmp
    networks:
      - docker-proxynet
      - app-net

networks:
  app-net:
    driver: bridge
  docker-proxynet:
    external: true
    name: komodoagent_docker-proxynet