version: "2"
services:
  smokeping:
    image: lscr.io/linuxserver/smokeping
    container_name: smokeping
    ports:
      - 80:80
    volumes:
      - ./config:/config
      - ./data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade
    hostname: zoidberg
    restart: unless-stopped