services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: always
    ports:
      - "80:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - mealie-data:/app/data/
    environment:
      - ALLOW_SIGNUP=false
      - ALLOW_PASSWORD_LOGIN=false
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://recipe.vukilis.com
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_AUTH_STRATEGY=${SMTP_AUTH_STRATEGY}
      - OIDC_AUTH_ENABLED=${OIDC_AUTH_ENABLED}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OIDC_CONFIGURATION_URL=${OIDC_CONFIGURATION_URL}
      - OIDC_SIGNUP_ENABLED=${OIDC_SIGNUP_ENABLED}
      - OIDC_USER_GROUP=${OIDC_USER_GROUP}
      - OIDC_ADMIN_GROUP=${OIDC_ADMIN_GROUP}
      - OIDC_AUTO_REDIRECT=${OIDC_AUTO_REDIRECT}
      - OIDC_PROVIDER_NAME=${OIDC_PROVIDER_NAME}
      - OIDC_REMEMBER_ME=${OIDC_REMEMBER_ME}
    labels:
      wud.trigger.include: docker.mealie

  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: 45876
      KEY: '${VAR_BESZEL_KEY}'
    labels:
      wud.trigger.include: docker.mealie

  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1
      - IMAGES=1
      - SERVICES=1
      - TASKS=1
      - INFO=1
      - POST=1
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    labels:
      wud.trigger.include: docker.mealie
volumes:
  mealie-data:
