services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    mem_limit: 500M

  traccar:
    image: traccar/traccar:latest
    container_name: traccar
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "80:8082"
      - "5000-5150:5000-5150"
      - "5000-5150:5000-5150/udp"
    volumes:
      - ./logs:/opt/traccar/logs:rw
      - ./traccar.xml:/opt/traccar/conf/traccar.xml:ro
      - ./data:/opt/traccar/data:rw
    #environment:
      #- JAVA_OPTS=-Xmx500M
    entrypoint: ["java", "-Xms200M", "-Xmx1g", "-Djava.net.preferIPv4Stack=true"]
    command: ["-jar", "tracker-server.jar", "conf/traccar.xml"]
    mem_limit: 200M
volumes:
  mysql_data:
