# roles/containers/task/main.yml  
# Role to prepare container template  
  
  - name: Update and upgrade apt packages
    ansible.builtin.apt:
      update_cache: yes
      upgrade: dist
      autoremove: yes
      purge: yes

  - name: Install common utilities
    ansible.builtin.apt:
      name: "{{ pkgs_debian }}"
      state: present
      update_cache: yes

  - name: Set nano as the default system editor
    community.general.alternatives:
      name: editor
      path: /bin/nano

  - name: Ensure the EDITOR environment variable is set globally
    ansible.builtin.lineinfile:
      path: /etc/environment
      line: 'EDITOR="nano"'
      state: present
      
  - name: Ensure the private group exists for each user
    ansible.builtin.group:
      name: "{{ item }}"
      state: present
    loop: "{{ users }}"

  - name: Create the admin user
    ansible.builtin.user:
      name: "{{ item }}"
      group: "{{ item }}"            
      groups: 
        - users
        - sudo
      append: yes            
      shell: /bin/bash        
      create_home: yes 
      password: "{{ user_password_hash }}"
    loop: "{{ users }}"

  - name: Create custom sudo rule for each user
    ansible.builtin.copy:
      content: "{{ item }} ALL=(ALL) NOPASSWD: /usr/bin/apt update"
      dest: "/etc/sudoers.d/{{ item }}_apt"
      owner: root
      group: root
      mode: '0440'
      validate: '/usr/sbin/visudo -cf %s'
    loop: "{{ users }}"

  - name: Allow 'sudo' group to use sudo without a password
    ansible.builtin.lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '%sudo ALL=(ALL:ALL) ALL'
      validate: 'visudo -cf %s'

  - name: Allow sudo to preserve TERMINFO for better terminal support
    ansible.builtin.lineinfile:
      path: /etc/sudoers
      state: present
      insertafter: '^Defaults'
      line: 'Defaults env_keep += "TERMINFO TERMINFO_DIRS"'
      validate: '/usr/sbin/visudo -cf %s'

  - name: Deploy SSH Public Key for admin user
    ansible.posix.authorized_key:
      user: "{{ item }}"
      state: present
      key: "{{ lookup('file', '~/.ssh/vuk.lekic.pub') }}"
    loop: "{{ users }}"

  - name: Reboot the server
    ansible.builtin.reboot:

  - name: Secure SSH Configuration
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      state: present
    loop:
      - { regexp: '^#?PermitRootLogin', line: 'PermitRootLogin no' }
      - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
    notify: Restart Services
    
  - name: Disable Root logins via shell
    ansible.builtin.user:
      name: root
      shell: /usr/sbin/nologin
      password_lock: yes

  - name: Script finished successfully
    ansible.builtin.debug:
      msg: "System secured. Root shell disabled. Use homelab for future access."
    delegate_to: localhost