services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - "80:4533"
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "./data:/data"
      - "/mnt/data:/music:ro"
    labels:
      wud.trigger.include: docker.navidrome
    networks:
        - docker-proxynet
        - app-net

  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    user: 65534:65534
    read_only: true
    mem_limit: 256M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    ports:
      - 45876:45876
    environment:
      PORT: 45876
      KEY: '${VAR_BESZEL_KEY}'
      DOCKER_HOST: "tcp://dockerproxy:2375"
    networks:
      - docker-proxynet
      - app-net

  dozzle-agent:
    image: amir20/dozzle:latest
    command: agent
    container_name: dozzle-agent
    restart: unless-stopped
    user: 65534:65534
    read_only: true
    mem_limit: 256M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    volumes:
      - ./tmp:/tmp
    ports:
      - 7007:7007
    environment:
      - PORT=7007
      - BESZEL_HOSTNAME=205-navidrome
      - DOCKER_HOST=tcp://dockerproxy:2375
      - HOME=/tmp
    networks:
      - docker-proxynet
      - app-net

networks:
  app-net:
    driver: bridge
  docker-proxynet:
    external: true
    name: komodoagent_docker-proxynet
