---
services:
  uptimekuma:
    image: louislam/uptime-kuma
    container_name: uptimekuma
    volumes:
       - ./uptimekuma-data:/app/data
    ports:
       - 80:3001
    dns:
      - 192.168.0.202
      - 1.1.1.1
      - 8.8.8.8
    restart: unless-stopped
    environment:
      DOCKER_HOST: "tcp://dockerproxy:2375"
    networks:
      - docker-proxynet
      - app-net
    labels:
      wud.trigger.include: docker.uptimekuma

  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    user: 65534:65534
    read_only: true
    mem_limit: 256M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    depends_on:
      - dockerproxy
    ports:
      - 45876:45876
    environment:
      PORT: 45876
      KEY: '${VAR_BESZEL_KEY}'
      DOCKER_HOST: "tcp://dockerproxy:2375"
    networks:
      - docker-proxynet
      - app-net
  dozzle-agent:
    image: amir20/dozzle:latest
    command: agent
    container_name: dozzle-agent
    restart: unless-stopped
    user: 65534:65534
    read_only: true
    mem_limit: 256M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    volumes:
      - ./tmp:/tmp
    depends_on:
      - dockerproxy
    ports:
      - 7007:7007
    environment:
      - PORT=7007
      - BESZEL_HOSTNAME="201-uptimekuma"
      - DOCKER_HOST=tcp://dockerproxy:2375
      - HOME=/tmp
      - DOZZLE_NO_STATS=true
    networks:
      - docker-proxynet
      - app-net
  dockerproxy:
    image: wollomatic/socket-proxy:1
    container_name: dockerproxy
    restart: unless-stopped
    user: "65534:${DOCKER_GID}"
    read_only: true
    mem_limit: 64M
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    command:
      - '-loglevel=info'
      - '-allowfrom=beszel-agent,dozzle-agent,uptimekuma'
      - '-listenip=0.0.0.0'
      - '-allowGET=(/v1\..{1,2})?/(containers/.*|images/.*|info|version|events.*|volumes|networks)'
      - '-allowHEAD=/_ping'
      - '-watchdoginterval=300'
      - '-stoponwatchdog'
      - '-shutdowngracetime=10'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - docker-proxynet
      
networks:
  docker-proxynet:
    internal: true
    attachable: false
  app-net:
    driver: bridge
    attachable: false
