services:
  wikidocs:
    image: zavy86/wikidocs
    ports:
      - 8084:80
    volumes:
      - ./wikidocs:/datasets
      - ./wikidocs/custom/submit.php:/var/www/localhost/htdocs/submit.php
      - ./wikidocs/custom/template.inc.php:/var/www/localhost/htdocs/template.inc.php
      - ./wikidocs/custom/Document.class.php:/var/www/localhost/htdocs/classes/Document.class.php
    restart: unless-stopped
    labels:
      wud.trigger.include: docker.local
networks: {}