---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 80:3000
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
      - ./icons:/app/public/icons
    environment:
      - DOCKER_HOST=tcp://dockerproxy:2375
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS}
      - LOG_LEVEL=debug
      - HOMEPAGE_VAR_PROXMOX_USERNAME=${HOMEPAGE_VAR_PROXMOX_USERNAME}
      - HOMEPAGE_VAR_PROXMOX_PASSWORD=${HOMEPAGE_VAR_PROXMOX_PASSWORD}
      - HOMEPAGE_VAR_PORTAINER_KEY=${HOMEPAGE_VAR_PORTAINER_KEY}
      - HOMEPAGE_VAR_QBITTORRENT_USERNAME=${HOMEPAGE_VAR_QBITTORRENT_USERNAME}
      - HOMEPAGE_VAR_QBITTORRENT_PASSWORD=${HOMEPAGE_VAR_QBITTORRENT_PASSWORD}
      - HOMEPAGE_VAR_NAVIDROME_USERNAME=${HOMEPAGE_VAR_NAVIDROME_USERNAME}
      - HOMEPAGE_VAR_NAVIDROME_TOKEN=${HOMEPAGE_VAR_NAVIDROME_TOKEN}
      - HOMEPAGE_VAR_NAVIDROME_SALT=${HOMEPAGE_VAR_NAVIDROME_SALT}
      - HOMEPAGE_VAR_ADGUARD_USERNAME=${HOMEPAGE_VAR_ADGUARD_USERNAME}
      - HOMEPAGE_VAR_ADGUARD_PASSWORD=${HOMEPAGE_VAR_ADGUARD_PASSWORD}
      - HOMEPAGE_VAR_PBS_USERNAME=${HOMEPAGE_VAR_PBS_USERNAME}
      - HOMEPAGE_VAR_PBS_PASSWORD=${HOMEPAGE_VAR_PBS_PASSWORD}
      - HOMEPAGE_VAR_MEDUSA_API=${HOMEPAGE_VAR_MEDUSA_API}
      - HOMEPAGE_VAR_AUTHENTIC_API=${HOMEPAGE_VAR_AUTHENTIC_API}
      - HOMEPAGE_VAR_NPM_USERNAME=${HOMEPAGE_VAR_NPM_USERNAME}
      - HOMEPAGE_VAR_NPM_PASSWORD=${HOMEPAGE_VAR_NPM_PASSWORD}
      - HOMEPAGE_VAR_CLOUDFLARE_ACCOUNTID=${HOMEPAGE_VAR_CLOUDFLARE_ACCOUNTID}
      - HOMEPAGE_VAR_CLOUDFLARE_TUNNELID=${HOMEPAGE_VAR_CLOUDFLARE_TUNNELID}
      - HOMEPAGE_VAR_CLOUDFLARE_TOKKEN=${HOMEPAGE_VAR_CLOUDFLARE_TOKKEN}
      - HOMEPAGE_VAR_WUD_USERNAME=${HOMEPAGE_VAR_WUD_USERNAME}
      - HOMEPAGE_VAR_WUD_PASSWORD=${HOMEPAGE_VAR_WUD_PASSWORD}
      - HOMEPAGE_VAR_BESZEL_USERNAME=${HOMEPAGE_VAR_BESZEL_USERNAME}
      - HOMEPAGE_VAR_BESZEL_PASSWORD=${HOMEPAGE_VAR_BESZEL_PASSWORD}
      - HOMEPAGE_VAR_GRAFANA_USERNAME=${HOMEPAGE_VAR_GRAFANA_USERNAME}
      - HOMEPAGE_VAR_GRAFANA_PASSWORD=${HOMEPAGE_VAR_GRAFANA_PASSWORD}
      - HOMEPAGE_VAR_KOMODO_KEY=${HOMEPAGE_VAR_KOMODO_KEY}
      - HOMEPAGE_VAR_KOMODO_SECRET=${HOMEPAGE_VAR_KOMODO_SECRET}
    logging:
      driver: loki
      options:
        loki-url: "http://${HOMEPAGE_VAR_LOKI_USERNAME}:${HOMEPAGE_VAR_LOKI_PASSWORD}@192.168.0.223:3100/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    restart: unless-stopped
    labels:
      wud.trigger.include: docker.homepage
    networks:
      - docker-proxynet
      - app-net  

  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    user: 65534:65534
    read_only: true
    mem_limit: 256M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    depends_on:
      - dockerproxy
    ports:
      - 45876:45876
    environment:
      PORT: 45876
      KEY: '${VAR_BESZEL_KEY}'
      DOCKER_HOST: "tcp://dockerproxy:2375"
    networks:
      - docker-proxynet
      - app-net

  dockerproxy:
    image: wollomatic/socket-proxy:1
    container_name: dockerproxy
    restart: unless-stopped
    user: "65534:${DOCKER_GID}"
    read_only: true
    mem_limit: 64M
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    command:
      - '-loglevel=info'
      - '-allowfrom=beszel-agent'
      - '-listenip=0.0.0.0'
      - '-allowGET=/v1\..{1,2}/(containers/.*|images/.*|info|version|events.*|volumes|networks)'
      - '-allowHEAD=/_ping'
      - '-watchdoginterval=300'
      - '-stoponwatchdog'
      - '-shutdowngracetime=10'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - docker-proxynet
      
networks:
  docker-proxynet:
    internal: true
    attachable: false
  app-net:
    driver: bridge
    attachable: false
