services:
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    environment:
      - WUD_WATCHER_LOCAL_CRON=0 6 * * *
      - WUD_WATCHER_LOCAL=unix:///var/run/docker.sock
      - WUD_TRIGGER_DOCKER_LOCAL_PRUNE=true
      - WUD_TRIGGER_DOCKER_LOCAL_AUTO=false
      # SERVER .201 (uptime-kuma)
      - WUD_WATCHER_UPTIMEKUMA_HOST=192.168.0.201
      - WUD_WATCHER_UPTIMEKUMA_CRON=0 6 * * *
      - WUD_WATCHER_UPTIMEKUMA_PORT=2375
      - WUD_TRIGGER_DOCKER_UPTIMEKUMA_PRUNE=true
      - WUD_TRIGGER_DOCKER_UPTIMEKUMA_AUTO=false
      # SERVER .203 (homepage)
      - WUD_WATCHER_HOMEPAGE_HOST=192.168.0.203
      - WUD_WATCHER_HOMEPAGE_CRON=0 6 * * *
      - WUD_WATCHER_HOMEPAGE_PORT=2375
      - WUD_TRIGGER_DOCKER_HOMEPAGE_PRUNE=true
      - WUD_TRIGGER_DOCKER_HOMEPAGE_AUTO=false
      # SERVER .205 (navidrome)
      - WUD_WATCHER_NAVIDROME_HOST=192.168.0.205
      - WUD_WATCHER_NAVIDROME_CRON=0 6 * * *
      - WUD_WATCHER_NAVIDROME_PORT=2375
      - WUD_TRIGGER_DOCKER_NAVIDROME_PRUNE=true
      - WUD_TRIGGER_DOCKER_NAVIDROME_AUTO=false
      # SERVER .206 (filebrowser)
      - WUD_WATCHER_FILEBROWSER_HOST=192.168.0.206
      - WUD_WATCHER_FILEBROWSER_CRON=0 6 * * *
      - WUD_WATCHER_FILEBROWSER_PORT=2375
      - WUD_TRIGGER_DOCKER_FILEBROWSER_PRUNE=true
      - WUD_TRIGGER_DOCKER_FILEBROWSER_AUTO=false
      # SERVER .207 (vaultwarden)
      - WUD_WATCHER_VAULTWARDEN_HOST=192.168.0.207
      - WUD_WATCHER_VAULTWARDEN_CRON=0 6 * * *
      - WUD_WATCHER_VAULTWARDEN_PORT=2375
      - WUD_TRIGGER_DOCKER_VAULTWARDEN_PRUNE=true
      - WUD_TRIGGER_DOCKER_VAULTWARDEN_AUTO=false
      # SERVER .210 (medusa)
      - WUD_WATCHER_MEDUSA_HOST=192.168.0.210
      - WUD_WATCHER_MEDUSA_CRON=0 6 * * *
      - WUD_WATCHER_MEDUSA_PORT=2375
      - WUD_TRIGGER_DOCKER_MEDUSA_PRUNE=true
      - WUD_TRIGGER_DOCKER_MEDUSA_AUTO=false
      # SERVER .219 (jetlog)
      - WUD_WATCHER_JETLOG_HOST=192.168.0.219
      - WUD_WATCHER_JETLOG_CRON=0 6 * * *
      - WUD_WATCHER_JETLOG_PORT=2375
      - WUD_TRIGGER_DOCKER_JETLOG_PRUNE=true
      - WUD_TRIGGER_DOCKER_JETLOG_AUTO=false
      # SERVER .220 (tools)
      - WUD_WATCHER_TOOLS_HOST=192.168.0.220
      - WUD_WATCHER_TOOLS_CRON=0 6 * * *
      - WUD_WATCHER_TOOLS_PORT=2375
      - WUD_TRIGGER_DOCKER_TOOLS_PRUNE=true
      - WUD_TRIGGER_DOCKER_TOOLS_AUTO=false
      # SERVER .222 (twingate)
      - WUD_WATCHER_TWINGATE_HOST=192.168.0.222
      - WUD_WATCHER_TWINGATE_CRON=0 6 * * *
      - WUD_WATCHER_TWINGATE_PORT=2375
      - WUD_TRIGGER_DOCKER_TWINGATE_PRUNE=true
      - WUD_TRIGGER_DOCKER_TWINGATE_AUTO=false # SERVER .223 (grafana)
      - WUD_WATCHER_GRAFANA_HOST=192.168.0.223
      - WUD_WATCHER_GRAFANA_CRON=0 6 * * *
      - WUD_WATCHER_GRAFANA_PORT=2375
      - WUD_TRIGGER_DOCKER_GRAFANA_PRUNE=true
      - WUD_TRIGGER_DOCKER_GRAFANA_AUTO=false
      # SERVER .224 (beszel)
      - WUD_WATCHER_BESZEL_HOST=192.168.0.224
      - WUD_WATCHER_BESZEL_CRON=0 6 * * *
      - WUD_WATCHER_BESZEL_PORT=2375
      - WUD_TRIGGER_DOCKER_BESZEL_PRUNE=true
      - WUD_TRIGGER_DOCKER_BESZEL_AUTO=false
      # SERVER .226 (mealie)
      - WUD_WATCHER_MEALIE_HOST=192.168.0.226
      - WUD_WATCHER_MEALIE_CRON=0 6 * * *
      - WUD_WATCHER_MEALIE_PORT=2375
      - WUD_TRIGGER_DOCKER_MEALIE_PRUNE=true
      - WUD_TRIGGER_DOCKER_MEALIE_AUTO=false
      # SERVER .227 (linkstack)
      - WUD_WATCHER_LINKSTACK_HOST=192.168.0.227
      - WUD_WATCHER_LINKSTACK_CRON=0 6 * * *
      - WUD_WATCHER_LINKSTACK_PORT=2375
      - WUD_TRIGGER_DOCKER_LINKSTACK_PRUNE=true
      - WUD_TRIGGER_DOCKER_LINKSTACK_AUTO=false
      # AUTH
      - WUD_AUTH_BASIC_VUKILIS_USER=${WUD_AUTH_BASIC_VUKILIS_USER}
      - WUD_AUTH_BASIC_VUKILIS_HASH=${WUD_AUTH_BASIC_VUKILIS_HASH}
      - TZ=Europe/Belgrade
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./whatsupdocker:/store
    ports:
      - 8085:3000
    restart: unless-stopped
    networks: {}
    labels:
      wud.trigger.include: docker.local
networks: {}