services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    user: 65534:65534
    read_only: true
    mem_limit: 256M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    depends_on:
      - dockerproxy
    ports:
      - 8082:8080
    environment:
      DOCKER_HOST: "tcp://dockerproxy:2375"
      DOZZLE_REMOTE_AGENT: "192.168.0.224:7007,192.168.0.201:7007,192.168.0.203:7007,192.168.0.206:7007,192.168.0.206:7007,192.168.0.210:7007,192.168.0.212:7007,192.168.0.217:7007,192.168.0.214:7007,192.168.0.220:7007,192.168.0.219:7007,192.168.0.222:7007,192.168.0.223:7007,192.168.0.224:7007,192.168.0.229:7007,192.168.0.226:7007,192.168.0.225:7007,192.168.0.227:7007,192.168.0.228:7007,192.168.0.232:7007,192.168.0.233:7007,192.168.0.234:7007"

    restart: unless-stopped
    labels:
      wud.trigger.include: docker.local
    networks:
      - docker-proxynet
      - app-net
    
  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    user: 65534:65534
    read_only: true
    mem_limit: 256M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    depends_on:
      - dockerproxy
    ports:
      - 45876:45876
    environment:
      PORT: 45876
      KEY: '${VAR_BESZEL_KEY}'
      DOCKER_HOST: "tcp://dockerproxy:2375"
    networks:
      - docker-proxynet
      - app-net

  dockerproxy:
    image: wollomatic/socket-proxy:1
    container_name: dockerproxy
    restart: unless-stopped
    user: "65534:${DOCKER_GID}"
    read_only: true
    mem_limit: 64M
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    command:
      - '-loglevel=info'
      - '-allowfrom=beszel-agent,dozzle'
      - '-listenip=0.0.0.0'
      - '-allowGET=/v1\..{1,2}/(containers/.*|images/.*|info|version|events.*|volumes|networks)'
      - '-allowHEAD=/_ping'
      - '-watchdoginterval=300'
      - '-stoponwatchdog'
      - '-shutdowngracetime=10'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - docker-proxynet
      
networks:
  docker-proxynet:
    internal: true
    attachable: false
  app-net:
    driver: bridge
    attachable: false