---
# HOMELAB TAB
- Networking:
    - Huawei:
        id: col-small
        href: http://huawei.lan
        icon: huawei.png
        description: ISP Router
        siteMonitor: http://huawei.lan
    - Archer C6:
        id: col-small
        href: http://archer.lan
        icon: tp-link.png
        description: Home Router
        siteMonitor: http://archer.lan
    - Horaco:
        href: http://horaco.lan
        icon: mdi-switch
        description: Switch
        siteMonitor: http://horaco.lan
    - Speedtest Tracker:
        href: http://speedtest.lan:8081
        description: Internet Speed Test
        icon: speedtest-tracker.png
        siteMonitor: http://speedtest.lan:8081
        widget:
            type: speedtest
            url: http://speedtest.lan:8081
            bitratePrecision: 3 # optional, default is 0

- Infrastructure and Data:
    - Proxmox:
        id: col-small
        href: https://proxmox.lan:8006
        icon: proxmox.png
        description: Proxmox Virtual Environment
        siteMonitor: https://proxmox.lan:8006
        widget:
            type: proxmox
            url: https://proxmox.lan:8006
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
    - Proxmox Backup Server:
        id: col-small
        href: https://pxm.backup.lan:8007
        icon: proxmox.png
        description: Proxmox Backup Server
        siteMonitor: https://pxm.backup.lan:8007
        widget:
            type: proxmoxbackupserver
            url: https://pxm.backup.lan:8007
            method: GET
            username: {{HOMEPAGE_VAR_PBS_USERNAME}}
            password: {{HOMEPAGE_VAR_PBS_PASSWORD}}
            allowSelfSigned: true
    - BlackBox:
        id: col-small
        icon: windows-11
        description: Linux - CachyOS
        ping: 192.168.0.152
    - HomePC:
        id: col-small
        icon: windows-10
        description: Windows 10 Operating System
        ping: 192.168.0.110
    - Turnkey-Fileserver:
        id: col-small
        href: http://fileserver.lan
        icon: https://www.turnkeylinux.org/files/images/icons/erver_0.jpg
        description: File Server
        siteMonitor: http://fileserver.lan
- Security and Identity:
    - AdGuard Home:
        id: col-small
        href: http://adblock.lan
        icon: adguard-home
        description: Ad Blocking
        siteMonitor: http://adblock.lan
        widget:
            type: adguard
            url: http://adblock.lan
            username: {{HOMEPAGE_VAR_ADGUARD_USERNAME}}
            password: {{HOMEPAGE_VAR_ADGUARD_PASSWORD}}
    - Authentik:
        id: col-small
        href: https://auth.vukilis.com/
        icon: authentik
        description: Authentication Provider
        siteMonitor: https://auth.vukilis.com/
        widget:
            type: authentik
            url: https://auth.vukilis.com/
            key: {{HOMEPAGE_VAR_AUTHENTIC_API}}
            version: 2
    - Vaultwarden:
        id: col-small
        href: https://vaultwarden.vukilis.com/
        icon: si-vaultwarden
        description: Password Manager
        siteMonitor: http://vaultwarden.lan
    - Twingate:
        id: col-small
        href: https://vukilis.twingate.com/
        icon: twingate
        description: VPN
        ping: 192.168.0.222

- Media & Entertainment:
    - qBittorrent:
        id: col-small
        href: http://qbittorrent.lan
        icon: qbittorrent  #si-qbittorrent
        description: Torrent Manager
        siteMonitor: http://qbittorrent.lan
        widget:
          type: qbittorrent
          url: http://qbittorrent.lan
          username: {{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}
          password: {{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}
    - Medusa:
        id: col-small
        href: http://medusa.lan
        icon: medusa
        description: Manager for TV Shows
        siteMonitor: http://medusa.lan
        widget:
          type: medusa
          url: http://medusa.lan
          key: {{HOMEPAGE_VAR_MEDUSA_API}}
    - Navidrome:
        id: col-small
        href: http://navidrome.lan
        icon: navidrome
        description: Music Server
        siteMonitor: http://navidrome.lan
        widget:
          type: navidrome
          url: http://navidrome.lan
          user: {{HOMEPAGE_VAR_NAVIDROME_USERNAME}}
          token: {{HOMEPAGE_VAR_NAVIDROME_TOKEN}} #md5(password + salt)
          salt: {{HOMEPAGE_VAR_NAVIDROME_SALT}}
    - FileBrowser:
        id: col-small
        href: http://filebrowser.lan:8080
        icon: filebrowser-quantum
        description: File Server
        siteMonitor: http://filebrowser.lan:8080

- Management:
    - Komodo:
        id: col-small
        href: https://komodo.vukilis.com
        icon: komodo
        description: Docker Compose Stack-Oriented Manager
        siteMonitor: http://komodo.lan:9120
        widget:
            type: komodo
            url: http://komodo.lan:9120
            method: GET
            key: {{HOMEPAGE_VAR_KOMODO_KEY}}
            secret: {{HOMEPAGE_VAR_KOMODO_SECRET}}
            showSummary: true
            showStacks: true
    - Nginx Proxy Manager:
        id: col-small
        href: https://npm.vukilis.com
        icon: nginx-proxy-manager
        description: Reverse Proxy Manager
        siteMonitor: http://npm.lan
        widget:
            type: npm
            url: http://npm.lan:81
            username: {{HOMEPAGE_VAR_NPM_USERNAME}}
            password: {{HOMEPAGE_VAR_NPM_PASSWORD}}
    - Cloudflared:
        id: col-small
        href: https://one.dash.cloudflare.com/
        icon: cloudflare-zero-trust
        description: Cloudflare Tunnels Manager
        widget:
          type: cloudflared
          accountid: {{HOMEPAGE_VAR_CLOUDFLARE_ACCOUNTID}}
          tunnelid: {{HOMEPAGE_VAR_CLOUDFLARE_TUNNELID}}
          key: {{HOMEPAGE_VAR_CLOUDFLARE_TOKKEN}}
    - n8n:
        id: col-small
        href: https://n8n.vukilis.com
        icon: n8n
        description: Workflow Automation Platform
        siteMonitor: http://n8n.lan:5678
    - Semaphore:
        id: col-small
        href: https://semaphore.vukilis.com
        icon: semaphore
        description: Infrastructure as Code Manager
        siteMonitor: http://semaphore.lan:3000

- Monitoring:
    - UptimeKuma:
        id: col-small
        href: https://status.vukilis.com/
        description: Downtime Monitoring
        icon: uptime-kuma.png
        siteMonitor: http://uptimekuma.lan
        widget:
            type: uptimekuma
            url: http://uptimekuma.lan
            slug: services
    - Netdata:
        id: col-small
        href: http://netdata.lan:19999
        description: Resource Monitoring
        icon: netdata.png
        siteMonitor: http://netdata.lan:19999
        widget:
            type: netdata
            url: http://netdata.lan:19999
    - Grafana:
        id: col-small
        href: http://grafana.lan:3000
        description: Grafana Dashboard
        icon: grafana
        siteMonitor: http://grafana.lan:3000
        widget:
          type: grafana
          url: http://grafana.lan:3000
          username: {{HOMEPAGE_VAR_GRAFANA_USERNAME}}
          password: {{HOMEPAGE_VAR_GRAFANA_PASSWORD}}
    - What's Up Docker:
        id: col-small
        href: https://wud.vukilis.com
        icon: whats-up-docker
        description: Keep containers up-to-date!
        siteMonitor: http://wud.lan:8085
        widget:
          type: whatsupdocker
          url: http://wud.lan:8085
          username: {{HOMEPAGE_VAR_WUD_USERNAME}}
          password: {{HOMEPAGE_VAR_WUD_PASSWORD}}
    - Beszel:
        id: col-small
        href: http://beszel.lan:8090
        description: Docker Resource Monitoring
        icon: beszel
        siteMonitor: http://beszel.lan:8090
        widget:
          type: beszel
          url: http://beszel.lan:8090
          username: {{HOMEPAGE_VAR_BESZEL_USERNAME}}
          password: {{HOMEPAGE_VAR_BESZEL_PASSWORD}}
          version: 2
    - Dozzle:
        id: col-small
        href: http://dozzle.lan:8082
        description: Docker Logs Monitor
        icon: dozzle
        siteMonitor: http://dozzle.lan:8082
    - WatchYourLan:
        id: col-small
        href: http://watchyourlan.lan:8840
        description: Network IP Scanner
        icon: watchyourlan
        siteMonitor: http://watchyourlan.lan:8840
    - SmokePing:
        id: col-small
        href: http://smokeping.lan
        description: Latency Measurement Tool
        icon: smokeping
        siteMonitor: http://smokeping.lan
    - Gotify:
        id: col-small
        href: https://notifications.vukilis.com
        description: Latency Measurement Tool
        icon: gotify
        siteMonitor: http://gotify.lan:8080
        widget:
          type: gotify
          url: https://notifications.vukilis.com
          key: {{HOMEPAGE_VAR_GOTIFY_KEY}}
- Utilities:
    - HomeLab Diagram:
        id: col-small
        icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/draw-io.png
        href: https://vukilis.com/homelab_diagram
        description: My HomeLab Diagram
        siteMonitor: https://vukilis.com/homelab_diagram
    - Usememos:
        id: col-small
        href: https://notepad.vukilis.com/
        icon: https://raw.githubusercontent.com/usememos/memos/refs/heads/main/web/public/logo.webp
        description: Notepad Server
        siteMonitor: http://usememos.lan
    - Wikidocs:
        id: col-small
        href: http://wikidocs.lan:8084
        icon: wikidocs
        description: Wiki Engine for documentation
        siteMonitor: http://wikidocs.lan:8084
    - Wallos:
        id: col-small
        href: https://wallos.vukilis.com
        icon: wallos
        description: Personal Subscription Tracker
        siteMonitor: http://wallos.lan:8282
    - Alpine-IT-Tools:
        id: col-small
        href: https://tools.vukilis.com
        icon: it-tools
        description: Various IT Tasks & Tools For Admins
        siteMonitor: http://tools.lan
    - Jetlog:
        id: col-small
        href: http://jetlog.lan
        icon: https://raw.githubusercontent.com/pbogre/jetlog/refs/heads/main/client/public/favicon.png
        description: Personal Flight Tracker
        siteMonitor: http://jetlog.lan
    - Traccar:
        id: col-small
        href: https://gps.vukilis.com
        icon: traccar
        description: GPS Tracking Software
        siteMonitor: http://traccar.lan
    - Mealie:
        id: col-small
        href: https://recipe.vukilis.com
        icon: mealie
        description: Recipe Manager
        siteMonitor: http://recipe.lan
    - Linkstack:
        id: col-small
        href: https://links.vukilis.com
        icon: linkstack
        description: Link Sharing Platform
        siteMonitor: http://links.lan:8080

- IoT and Smarthome:
    - Home Assistant:
        id: col-small
        href: http://homeassistant.lan:8123
        icon: home-assistant
        description: Smart Home Management
        siteMonitor: http://homeassistant.lan:8123

#BOOKMARKS TAB
- Search Engine & AI:
    - Google:
        id: col-small
        href: https://www.google.rs
        icon: google
    - Brave:
        id: col-small
        href: https://search.brave.com/
        icon: brave
    - DuckDuckGo:
        id: col-small
        href: https://duckduckgo.com/
        icon: duckduckgo
    - Perplexity:
        id: col-small
        href: https://perplexity.ai/
        icon: perplexity
    - ChatGPT:
        id: col-small
        href: https://chatgpt.com/
        icon: chatgpt
    - Deepseek:
        id: col-small
        href: https://deepseek.com/
        icon: deepseek
    - Copilot:
        id: col-small
        href: https://copilot.microsoft.com/
        icon: microsoft-copilot
    - Google AI Studio:
        id: col-small
        href: https://aistudio.google.com/prompts/new_chat
        icon: https://www.gstatic.com/aistudio/ai_studio_favicon_2_32x32.png
    - Gemini:
        id: col-small
        href: https://gemini.google.com/
        icon: google-gemini
    - Grok:
        id: col-small
        href: https://grok.com/
        icon: grok
- Online Entertainment:
    - Youtube:
        id: col-small
        href: https://www.youtube.com
        icon: youtube
    - Twitch:
        id: col-small
        href: https://www.twitch.tv
        icon: twitch
    - Kick:
        id: col-small
        href: https://www.kick.com
        icon: kick
    - IMDB:
        id: col-small
        href: https://www.imdb.com
        icon: https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/favicon_desktop_32x32._CB1582158068_.png
    - Releases:
        id: col-small
        href: https://www.releases.com/
        icon: https://www.releases.com/resources/image/fav_32x32.png
    - Titlovi:
        id: col-small
        href: https://rs.titlovi.com/?v=1
        icon: https://static.titlovi.com/titlovicom/Content/Images/logo-big.png
    - Subtitletools:
        id: col-small
        href: https://subtitletools.com/merge-subtitles-online
        icon: https://subtitletools.com/favicon.png
    - Pionex:
        id: col-small
        href: https://www.pionex.com/en/
        icon: https://pbs.twimg.com/media/GQbu0yFaIAYeJGa.png
- Social Network:
    - Instagram:
        id: col-small
        href: https://www.instagram.com
        icon: instagram
    - Facebook:
        id: col-small
        href: https://www.facebook.com
        icon: facebook
    - TikTok:
        id: col-small
        href: https://www.tiktok.com/@vukilis
        icon: tiktok
    - Telegram:
        id: col-small
        href: https://web.telegram.org
        icon: telegram
    - Twitter:
        id: col-small
        href: https://www.twitter.com
        icon: twitter
    - Reddit:
        id: col-small
        href: https://www.reddit.com
        icon: reddit
    - Benchamark:
        id: col-small
        href: https://forum.benchmark.rs/
        icon: https://forum.benchmark.rs/data/avatars/s/13/13530.jpg?1675890762
    - Bandcamp:
        id: col-small
        href: https://www.vukilis.bandcamp.com
        icon: bandcamp
- Sports:
    - Euroleague:
        id: col-small
        href: https://www.euroleaguebasketball.net/euroleague/
        icon: https://www.euroleaguebasketball.net/favicon.ico
    - ABA League:
        id: col-small
        href: https://www.aba-liga.com
        icon: https://www.aba-liga.com/favicon.ico
    - Super liga Srbije:
        id: col-small
        href: https://www.superliga.rs
        icon: https://www.superliga.rs/wp-content/themes/newweb-theme/images/favicon/favicon.ico
    - Rezultati:
        id: col-small
        href: https://www.rezultati.com
        icon: https://static.flashscore.com/res/_fs/image/4_favicons/_fs/favicon.ico?v=8
    - RD Live:
        id: col-small
        href: https://rd-live.com/
        icon: https://rd-live.com/assets/favicon.svg
    - Utakmice Stream:
        id: col-small
        href: https://utakmice.stream/
        icon: https://utakmice.stream/wp-content/uploads/2018/05/cropped-US-Icon-512-32x32.png
    - Uzivo.utakmica Stream:
        id: col-small
        href: https://uzivo.utakmica.rs/
        icon: https://uzivo.utakmica.rs/favicon.svg?v=1.0.0
    - Messitv:
        id: col-small
        href: https://v1.messitv.net/2025/03/all-arena-sport-channels-full-hd.html
        icon: https://1.bp.blogspot.com/--rZOb4HNm34/YcSjeaN290I/AAAAAAAAAAM/PuBLLKsDccIlfwU7NVyDGEWb6NxHYNvPgCNcBGAsYHQ/s268/messi-tv.png
    - Rojadirectatv:
        id: col-small
        href: https://www.rojadirectatv.cv
        icon: https://www.rojadirectatv.cv/favicon.ico
    - Vipleague:
        id: col-small
        href: https://www.vipleague.pm/
        icon: https://www.vipleague.pm/favicon.ico
- Shop:
    - Wolt:
        id: col-small
        href: https://wolt.com/sr/srb
        icon: https://cdn-attachments.timesofmalta.com/9688165895420b5943f98d2cbe7a5d40d46e373b-1685019718-7bcde8b8-1920x1280.png
    - Glovo:
        id: col-small
        href: https://glovoapp.com/rs/sr/
        icon: https://tavernaamsterdam.com/wp-content/uploads/2023/04/glovo-2.png
    - AliExpress:
        id: col-small
        href: https://www.aliexpress.com/
        icon: https://webautomation.io/static/images/domain_images/aliexpress.png
    - Temu:
        id: col-small
        href: https://www.temu.com/
        icon: https://www.temu.com/favicon.ico
    - Eponuda:
        id: col-small
        href: https://www.eponuda.com/
        icon: https://www.eponuda.com/favicon.ico
    - KupujemProdajem:
        id: col-small
        href: https://www.kupujemprodajem.com/
        icon: https://www.kupujemprodajem.com/favicon.ico
    - Geizhals:
        id: col-small
        href: https://geizhals.at/
        icon: https://geizhals.at/favicon.ico
    - Mi Serbia:
        id: col-small
        href: https://mi-srbija.rs/
        icon: https://mi-srbija.rs/images/logo/xiaomi-global-logo.png
    - track24:
        id: col-small
        href: https://track24.net/
        icon: https://track24.net/favicon.ico
    - Global Cainiao :
        id: col-small
        href: https://global.cainiao.com/
        icon: https://img.alicdn.com/tfs/TB1CZ0ARpXXXXX7XXXXXXXXXXXX-32-32.png
    - Parcelsapp:
        id: col-small
        href: https://parcelsapp.com
        icon: https://parcelsapp.com/favicon.ico
    - Magyar Posta:
        id: col-small
        href: https://www.posta.hu/
        icon: https://www.posta.hu/favicon.ico
- Torrents:
    - Fmhy:
        id: col-small
        href: https://fmhy.pages.dev/
        icon: https://fmhy.pages.dev/fmhy.ico
        description: Torrent Collection
    - Damag:
        id: col-small
        href: https://damag.net/
        icon: https://d4.alternativeto.net/vi3mqXneYDJNe3MnGet3m8fkLunRG86iC07IjAB9qzo/rs:fit:280:280:0/g:ce:0:0/exar:1/YWJzOi8vZGlzdC9pY29ucy90b3JyZW50LWdhbGF4eV8yMTgwMjIucG5n.png
        description: Torrent
    - Knaben:
        id: col-small
        href: https://knaben.org/
        icon: https://knaben.org/favicon.ico
        description: Movies & Series
    - YIFY:
        id: col-small
        href: https://yts.gg/home
        icon: https://yts.gg/assets/images/website/favicon.ico
        description: Movies & Series
    - Arcadepunks:
        id: col-small
        href: https://www.arcadepunks.com/
        icon: https://www.arcadepunks.com/wp-content/uploads/2026/06/Arcade-Punks-Logo.webp
        description: Retro Gaming
    - CS.RIN.RU ETS2:
        id: col-small
        href: https://cs.rin.ru/forum/viewtopic.php?f=10&t=63279&hilit=euro+truck
        icon: https://i0.wp.com/cs.rin.ru/forum/styles/rinDark/imageset/site_logo-2.png
        description: Forum For ETS2 Cracks
    - CS.RIN.RU:
        id: col-small
        href: https://cs.rin.ru/forum/viewtopic.php?f=10&t=95461
        icon: https://i0.wp.com/cs.rin.ru/forum/styles/rinDark/imageset/site_logo-2.png
        description: Forum For Cracks
    - Dodi:
        id: col-small
        href: https://dodi-repacks.site/
        icon: https://styles.redditmedia.com/t5_ab6jz1/styles/communityIcon_fv793fnur75c1.png
        description: Repacks
    - Fitgirl:
        id: col-small
        href: https://fitgirl-repacks.site/
        icon: https://fitgirl-repacks.site/wp-content/uploads/2016/08/cropped-icon-32x32.jpg
        description: Repacks
    - Online-fix:
        id: col-small
        href: https://online-fix.me/
        icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgve7LDrfkGC31pGhpmcZIT5ZdXVrT3ZZhtg&s
        description: Online Crack
    - Flingtrainer:
        id: col-small
        href: https://flingtrainer.com/
        icon: https://cdn-b.saashub.com/images/app/service_logos/188/1pp5meaqd72y/large.png?1630233633
        description: Cheats and Mods
    - GameDrive:
        id: col-small
        href: https://gamedrive.org/
        icon: https://gamedrive.org/wp-content/uploads/2023/06/logo.png
        description: Adobe Cracks
    - Monkrus:
        id: col-small
        href: https://w18.monkrus.ws/
        icon: https://w18.monkrus.ws/favicon.ico
        description: Adobe Cracks
- Linux:
    - Flathub:
        id: col-small
        href: https://flathub.org/
        icon: flathub-dark
    - ChrisTitusGIT:
        id: col-small
        href: https://github.com/ChrisTitusTech
        icon: github-light
    - ChrisTitus:
        id: col-small
        href: https://christitus.com/
        icon: https://christitus.com/images/favicon.png
    - ArchWiki:
        id: col-small
        href: https://wiki.archlinux.org
        icon: https://wiki.archlinux.org/favicon.ico
    - LiNUX:
        id: col-small
        href: https://www.linux.com/
        icon: https://www.linux.com/wp-content/uploads/2019/08/favicon-300x300.png
    - distrowatch:
        id: col-small
        href: https://distrowatch.com/
        icon: https://distrowatch.com/favicon.ico
    - thelinuxbook:
        id: col-small
        href: https://thelinuxbook.com/
        icon: https://thelinuxbook.com/favicon.png
    - Distrosea:
        id: col-small
        href: https://distrosea.com/
        icon: https://distrosea.com/favicon-32x32.png
- Gaming & Tech News:
    - Svet Kompjutera:
        id: col-small
        href: https://www.sk.rs/pocetna
        icon: https://www.sk.rs/favicon.ico
    - Play.co:
        id: col-small
        href: https://play.co.rs/
        icon: https://play.co.rs/wp-content/uploads/2019/03/playzineW.png
    - HCL:
        id: col-small
        href: https://www.hcl.hr/
        icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKFs0osUmLpIo26oGVbUzSnhRGwGIvICGnsQ&s
    - Gamerant:
        id: col-small
        href: https://gamerant.com/gaming/
        icon: https://gamerant.com/public/build/images/favicon-192x192.png
    - Bleepingcomputer:
        id: col-small
        href: https://www.bleepingcomputer.com/
        icon: https://www.bleepingcomputer.com/favicon.ico
    - Tweaktown:
        id: col-small
        href: https://www.tweaktown.com/
        icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNqXTOHrhM2f9xGigcMhHdr7QXkwCq12vTSQ&s
    - Arstechnica:
        id: col-small
        href: https://arstechnica.com/
        icon: https://arstechnica.com/favicon.ico
    - TheVerge:
        id: col-small
        href: https://www.theverge.com/
        icon: https://cdn.vox-cdn.com/verge/favicon.ico
    - HackerNews:
        id: col-small
        href: https://news.ycombinator.com/
        icon: https://news.ycombinator.com/favicon.ico
    - TheHackerNews:
        id: col-small
        href: https://thehackernews.com/
        icon: https://thehackernews.com/favicon.ico
    - Hacktricks:
        id: col-small
        href: https://book.hacktricks.wiki/
        icon: https://book.hacktricks.wiki/favicon.png
    - Darkreading:
        id: col-small
        href: https://www.darkreading.com/
        icon: https://www.darkreading.com/favicon.ico
    - Cvemon:
        id: col-small
        href: https://cvemon.intruder.io/
        icon: https://cvemon.intruder.io/favicon.ico
    - Survey Stackoverflow:
        id: col-small
        href: https://survey.stackoverflow.co/
        icon: https://survey.stackoverflow.co/legacy-assets/Sites/stackoverflow/Img/favicon3804.ico?v=ec617d715196
    - Idiokratija:
        id: col-small
        href: https://idiokratija.com/
        icon: https://idiokratija.com/favicon.ico
- Gaming Clients & Info:
    - Steam:
        id: col-small
        href: https://store.steampowered.com/
        icon: https://store.steampowered.com/favicon.ico
    - Epic:
        id: col-small
        href: https://store.epicgames.com/en-US/
        icon: https://static-assets-prod.epicgames.com/epic-store/static/favicon.ico
    - GOG Galaxy:
        id: col-small
        href: https://www.gog.com/galaxy
        icon: https://gogalaxy.gog-statics.com/build/images/galaxy-logo-fa7b4b2d.png
    - Xbox:
        id: col-small
        href: https://www.xbox.com/en-US/
        icon: https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Xbox_one_logo.svg/2048px-Xbox_one_logo.svg.png
    - Path Of Exile:
        id: col-small
        href: https://pathofexile.com/
        icon: https://pathofexile.com/favicon.ico
    - Path Of Exile 2:
        id: col-small
        href: https://pathofexile2.com/
        icon: https://web.poecdn.com/protected/image/favicon/poe2/favicon.ico?key=z1ntMm_mlpgr2cNrStO09g
    - NexusMods:
        id: col-small
        href: https://www.nexusmods.com/
        icon: https://www.nexusmods.com/favicon.ico
    - steamdb.info:
        id: col-small
        href: https://steamdb.info/sales/history/
        icon: https://steamdb.info/favicon.ico
    - HowLongToBeat:
        id: col-small
        href: https://www.howlongtobeat.com/
        icon: https://www.howlongtobeat.com/favicon.ico
- FileSharing:
    - Google Drive:
        id: col-small
        href: https://drive.google.com/drive
        icon: https://ssl.gstatic.com/images/branding/product/1x/drive_2020q4_48dp.png
    - Pixeldrain:
        id: col-small
        href: https://pixeldrain.com
        icon: https://pixeldrain.com/res/img/pixeldrain_256.png
    - ShareMods:
        id: col-small
        href: https://sharemods.com/
        icon: https://sharemods.com/images/why-us-image-3.png
    - Paster:
        id: col-small
        href: https://paster.so/
        icon: https://paster.so/brand/assets/icon/standard.svg
    - Streamable:
        id: col-small
        href: https://streamable.com/
        icon: https://streamable.com/favicon.ico
    - Dropbox:
        id: col-small
        href: https://dropbox.com/
        icon: dropbox
- Tools:
    - Mchose:
        id: col-small
        href: https://www.mchose.com.cn/
        icon: https://www.mchose.com.cn/mchose.ico
    - Webpagetest:
        id: col-small
        href: https://www.webpagetest.org/
        icon: https://cdn.prod.website-files.com/61027bb0bc31fc6cafefbc0c/65c6757401e600138a7a44e3_home-globe-bg.avif
    - Proxmox VE Helper-Scripts:
        id: col-small
        href: https://community-scripts.github.io/ProxmoxVE/
        icon: https://community-scripts.github.io/ProxmoxVE/logo.png
    - Check My DNS:
        id: col-small
        href: https://cmdns.dev.dns-oarc.net/
        icon: https://dev.dns-oarc.net/favicon.ico
    - whatsmydns:
        id: col-small
        href: https://www.whatsmydns.net/
        icon: https://www.whatsmydns.net/favicon.ico
    - check-host:
        id: col-small
        href: https://check-host.net/
        icon: https://check-host.net/favicon.ico
    - mxtoolbox:
        id: col-small
        href: https://mxtoolbox.com/
        icon: https://mxtoolbox.com/favicon.ico
    - Asciiflow:
        id: col-small
        href: https://asciiflow.com
        icon: https://raw.githubusercontent.com/lewish/asciiflow/refs/heads/main/client/public/favicon.png
    - comparetwolists:
        id: col-small
        href: https://comparetwolists.com/
        icon: https://comparetwolists.com/favicon.ico
    - Fetchrss:
        id: col-small
        href: https://fetchrss.com/
        icon: https://fetchrss.com/favicon.ico
    - Excalidraw:
        id: col-small
        href: https://excalidraw.com/
        icon: https://excalidraw.com/favicon.ico
    - Eloshapes:
        id: col-small
        href: https://www.eloshapes.com/
        icon: https://www.eloshapes.com/logo/white.svg
- Dev Tools:
    - Trello:
        id: col-small
        href: https://trello.com/
        icon: atlassian-trello
        description: Project Manager
    - Figma:
        id: col-small
        href: https://figma.com/
        icon: https://static.figma.com/app/icon/1/favicon.ico
        description: Project Manager
    - Suno:
        id: col-small
        href: https://suno.com/
        icon: https://cdn-o.suno.com/favicon-192x192.png
        description: Project Manager
    - HRTF Database:
        id: col-small
        href: https://airtable.com/appayGNkn3nSuXkaz/shruimhjdSakUPg2m/tbloLjoZKWJDnLtTc
        icon: https://airtable.com/images/favicon/baymax/android-chrome-192x192.png?v=2
        description: HeSuVi Database
    - AutoEq:
        id: col-small
        href: https://autoeq.app/
        icon: https://autoeq.app/favicon-32x32.png
        description: Headphone Equalization
    - linuxserver:
        id: col-small
        href: https://www.linuxserver.io/
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/webp/linuxserver-io.webp
        description: Docker images
    - selfh:
        id: col-small
        href: https://selfh.st/icons/
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/webp/selfh-st.webp
        description: Dashboard Icons
- Travel:
    - Booking:
        id: col-small
        href: https://www.booking.com/
        icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVqpq-6zK3cs6d6dFWCxF4QXs1AjqVuKwsmQ&s
        description: Travel Services
    - Flightradar24:
        id: col-small
        href: https://my.flightradar24.com/
        icon: https://my.flightradar24.com/favicon.ico
        description: Flight Logbook
    - Lufthansa:
        id: col-small
        href: https://www.lufthansa.com/gb/en/homepage
        icon: https://www.lufthansa.com/favicon.ico
        description: Airlines
    - Saily:
        id: col-small
        href: https://saily.com/
        icon: https://saily.com/favicon-32x32.png
        description: eSIM
    - Kiwi:
        id: col-small
        href: https://www.kiwi.com/us/
        icon: https://images.kiwi.com/common/kiwicom-logo-mobile-no-whitespace.svg
        description: Travel Agency
    - Momodo:
        id: col-small
        href: https://www.momondo.com/
        icon: https://www.momondo.com/favicon.ico
        description: Travel Deals
    - iatatravelcentre:
        id: col-small
        href: https://www.iatatravelcentre.com/
        icon: https://www.iata.org/favicon-32x32.png
        description: Travel Deals
