version: "3.3"
services:
  memos:
    container_name: memos
    ports:
      - 80:5230
    volumes:
      - .memos/:/var/opt/memos
    image: neosmemo/memos:stable
    restart: unless-stopped
networks: {}