services:
  planka:
    image: ghcr.io/plankanban/planka:2.0.0-rc.2
    restart: on-failure
    volumes:
      - favicons:/app/public/favicons
      - user-avatars:/app/public/user-avatars
      - background-images:/app/public/background-images
      - attachments:/app/private/attachments
    ports:
      - 8083:1337
    environment:
      - BASE_URL=https://planka.vukilis.com
      - DATABASE_URL=postgresql://postgres:$${DATABASE_PASSWORD}@postgres/planka

      - SECRET_KEY=${SECRET_KEY}
      # - LOG_LEVEL=warn

      - TRUST_PROXY=true
      # - TOKEN_EXPIRES_IN=365 # In days
      - DEFAULT_LANGUAGE=en-US
      - DEFAULT_ADMIN_EMAIL=${DEFAULT_ADMIN_EMAIL}
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}
      - DEFAULT_ADMIN_NAME=${DEFAULT_ADMIN_NAME}
      - DEFAULT_ADMIN_USERNAME=${DEFAULT_ADMIN_NAME}
      - ACTIVE_USERS_LIMIT=1
      # - SHOW_DETAILED_AUTH_ERRORS=false

    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:16-alpine
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres -d planka
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  favicons: null
  user-avatars: null
  background-images: null
  attachments: null
  db-data: null
networks: {}