services:
  filebrowser:
    image: gtstef/filebrowser:beta
    environment:
      FILEBROWSER_CONFIG: "data/config.yaml" # overrides the default path which is ./config.yaml
      FILEBROWSER_ADMIN_PASSWORD: ${PASSWORD}
      TZ: "Europe/Belgrade"
    #user: 0:0
    user: filebrowser
    volumes:
      - /mnt:/files
      - ./data:/home/filebrowser/data
    ports:
      - 8080:80
    restart: unless-stopped
    labels:
      wud.trigger.include: docker.filebrowser

  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: 45876
      KEY: '${VAR_BESZEL_KEY}'
    labels:
      wud.trigger.include: docker.filebrowser

  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1
      - IMAGES=1
      - SERVICES=1
      - TASKS=1
      - INFO=1
      - POST=1
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    labels:
      wud.trigger.include: docker.filebrowser
