services:
  filebrowser:
    image: gtstef/filebrowser:beta
    container_name: filebrowser
    environment:
      FILEBROWSER_CONFIG: "data/config.yaml"
      FILEBROWSER_ADMIN_PASSWORD: ${PASSWORD}
      TZ: "Europe/Belgrade"
      DOCKER_HOST: "tcp://dockerproxy:2375"

    user: filebrowser
    volumes:
      - /mnt:/files
      - ./data:/home/filebrowser/data
    ports:
      - 8080:80
    restart: unless-stopped
    labels:
      wud.trigger.include: docker.filebrowser
    networks:
      - docker-proxynet
      - app-net

  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    user: 65534:65534
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    depends_on:
      - dockerproxy
    ports:
      - 45876:45876
    environment:
      PORT: 45876
      KEY: '${VAR_BESZEL_KEY}'
      DOCKER_HOST: "tcp://dockerproxy:2375"
    networks:
      - docker-proxynet
      - app-net

  dockerproxy:
    image: wollomatic/socket-proxy:1
    container_name: dockerproxy
    restart: unless-stopped
    user: "65534:$(DOCKER_GID)"
    read_only: true
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    command:
      - '-loglevel=info'
      - '-allowfrom=beszel-agent,container_name'
      - '-listenip=0.0.0.0'
      - '-allowGET=(/v1\..{1,2})?/(containers/.*|images/.*|info|version|events.*|volumes|networks)'
      - '-allowHEAD=/_ping'
      - '-watchdoginterval=300'
      - '-stoponwatchdog'
      - '-shutdowngracetime=10'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - docker-proxynet
      
networks:
  docker-proxynet:
    internal: true
    attachable: false
  app-net:
    driver: bridge
    attachable: false