services:
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    environment:
      - WUD_AUTH_BASIC_VUKILIS_USER=${WUD_AUTH_BASIC_VUKILIS_USER}
      - WUD_AUTH_BASIC_VUKILIS_HASH=${WUD_AUTH_BASIC_VUKILIS_HASH}
      - TZ=Europe/Belgrade
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./whatsupdocker:/store
    ports:
      - 8085:3000
    restart: unless-stopped
    networks: {}
networks: {}