---
networks:
  frontend:
    external: true
  backend:
    external: true
services:
  twingate:
    container_name: twingate-connector-1
    image: twingate/connector:1
    environment:
      - TWINGATE_NETWORK=vukilis
      - TWINGATE_DNS=192.168.0.202
      - TWINGATE_ACCESS_TOKEN=${TWINGATE_ACCESS_TOKEN}
      - TWINGATE_REFRESH_TOKEN=${TWINGATE_REFRESH_TOKEN}
      - TWINGATE_LOG_LEVEL=1
      - TWINGATE_LABEL_DEPLOYED_BY=docker
    networks:
      - frontend
      - backend
    restart: unless-stopped
    labels:
      wud.trigger.include: docker.twingate

  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: 45876
      KEY: '${VAR_BESZEL_KEY}'
