---
services:
  grafana:
    image: docker.io/grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    user: '1000'
    restart: unless-stopped
    labels:
      wud.trigger.include: docker.grafana
    environment:
      - DOCKER_HOST=tcp://dockerproxy:2375
    depends_on:
      - node-exporter
      - prometheus
      - loki
      - dockerproxy
    networks:
      - docker-proxynet
      - app-net

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    user: '1000'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - app-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    user: '1000'
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    labels:
      wud.trigger.include: docker.grafana
    networks:
      - app-net

  loki:
    container_name: loki
    image: docker.io/grafana/loki:latest
    command: "-config.file=/etc/loki/config.yaml"
    ports:
      - 3100:3100
    volumes:
      - ./config/config.yaml:/etc/loki/config.yaml:ro
      - data-loki:/loki:rw
    user: '1000'
    restart: unless-stopped
    labels:
      wud.trigger.include: docker.grafana
    networks:
      - app-net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    command:
      - "--housekeeping_interval=30s"
      - "--docker_only=true"
      - "--disable_metrics=percpu,sched,tcp,udp,disk,diskIO,hugetlb,referenced_memory,cpu_topology,resctrl"
      - "--store_container_labels=false"
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped
    labels:
      wud.trigger.include: docker.grafana
    networks:
      - app-net

  promtail:
    image: docker.io/grafana/promtail:latest
    command: "-config.file=/mnt/config/promtail.yaml"
    volumes:
      - ./config/promtail.yaml:/mnt/config/promtail.yaml:ro
      - /var/log:/var/log:ro
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push 
      - VAR_LOKI_USERNAME=${VAR_LOKI_USERNAME}
      - VAR_LOKI_PASSWORD=${VAR_LOKI_PASSWORD}
    restart: unless-stopped
    labels:
      wud.trigger.include: docker.grafana
    networks:
      - app-net

  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    user: 65534:65534
    read_only: true
    mem_limit: 256M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    depends_on:
      - dockerproxy
    ports:
      - 45876:45876
    environment:
      PORT: 45876
      KEY: '${VAR_BESZEL_KEY}'
      DOCKER_HOST: "tcp://dockerproxy:2375"
    networks:
      - docker-proxynet
      - app-net

  dockerproxy:
    image: wollomatic/socket-proxy:1
    container_name: dockerproxy
    restart: unless-stopped
    user: "65534:${DOCKER_GID}"
    read_only: true
    mem_limit: 64M
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    command:
      - '-loglevel=info'
      - '-allowfrom=beszel-agent,grafana'
      - '-listenip=0.0.0.0'
      - '-allowGET=/v1\..{1,2}/(containers/.*|images/.*|info|version|events.*|volumes|networks)'
      - '-allowHEAD=/_ping'
      - '-watchdoginterval=300'
      - '-stoponwatchdog'
      - '-shutdowngracetime=10'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - docker-proxynet
      
networks:
  docker-proxynet:
    internal: true
    attachable: false
  app-net:
    driver: bridge
    attachable: false

volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local
  data-loki:
    driver: local
