services:
  netalertx:                                 
    container_name: netalertx                
    image: ghcr.io/jokob-sk/netalertx:latest      
    network_mode: "host" 
    restart: unless-stopped
    user: 65534:65534
    read_only: true
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN                                   # Required for ARP scanning
      - NET_RAW                                     # Required for raw socket operations
      - NET_BIND_SERVICE                            # Required to bind to privileged ports (nbtscan)
    volumes:
      - ./config/app.conf:/data/config/app.conf 
      - ./db/app.db:/data/db/app.db             
      - ./logs:/tmp/log
      - ./tmp:/tmp
      - type: bind                                  
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    environment:
        LISTEN_ADDR: 0.0.0.0
        PORT: 20211                                 
        GRAPHQL_PORT: 20212
        HOME: /tmp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"   