# ansible/packages.yml
# This file contains lists of packages to be installed via Ansible.
pkgs_debian:
  - acpid
  - atop
  - bash-completion
  - bind9-dnsutils
  - curl
  - dos2unix
  - elinks
  - ethtool
  - git
  - htop
  - iperf3
  - iotop
  - iptraf
  - lsof
  - lshw
  - ltrace
  - molly-guard
  - nano
  - ncdu
  - net-tools
  - netcat-traditional
  - pciutils
  - plocate
  - pydf
  - rsync
  - strace
  - sudo
  - sysstat
  - tcpdump
  - telnet
  - tmux
  - traceroute
  - unzip
  - vim
  - wget
  - zip
  - zstd

pkgs_alpine:
  - acpid
  - atop
  - bash
  - bash-completion
  - bind-tools
  - curl
  - dos2unix
  - elinks
  - ethtool
  - git
  - htop
  - iperf3
  - iotop
  - lsof
  - ltrace
  - nano
  - ncdu
  - net-tools
  - pciutils
  - rsync
  - strace
  - sudo
  - sysstat
  - tcpdump
  - tmux
  - util-linux
  - unzip
  - vim
  - wget
  - zip
  - zstd