---

- hosts: "{{ hosts }}"
  vars_files:
    - users.yml
    - packages.yml
  remote_user: "{{ remote_user }}"
  become: true
  gather_facts: yes                   # no/yes for Alpine Linux compatibility
  roles:
    # - debian-containers             # Role to prepare container template
    # - alpine-containers             # Role to prepare container template for Alpine Linux

    # - debian-install-docker         # Role to install Docker Engine and related components
    # - alpine-install-docker         # Role to install Docker Engine on Alpine Linux

    # - debian-comodo-agent-docker    # Role to deploy Komodo Agent container    
    # - alpine-comodo-agent-docker    # Role to deploy Komodo Agent container    

    # - cleanup-docker-resources      # Role to clean up unused Docker resources