
# roles/comodo-agent-docker/tasks/main.yml
# Deploy Komodo Agent Docker container

  - name: Create komodoagent directory
    file:
      path: "komodoagent"
      state: directory
      owner: "{{ item }}"
      group: "{{ item }}"
      mode: '0755'
    loop: "{{ users }}"

  - name: Create .env file
    copy:
      dest: "komodoagent/.env"
      content: |
        PERIPHERY_ROOT_DIRECTORY={{ periphery_root }}
        PASSKEY={{ passkey }}
        KOMODO_WEBHOOK_SECRET={{ KOMODO_WEBHOOK_SECRET }}
      owner: "{{ item }}"
      group: "{{ item }}"
      mode: '0600'
    loop: "{{ users }}"

  - name: Create stack directory
    file:
      path: "stack"
      state: directory
      owner: "{{ item }}"
      group: "{{ item }}"
      mode: '0755'
    loop: "{{ users }}"

  - name: Create komodo home directory
    file:
      path: "/etc/komodo"
      state: directory
      owner: "{{ item }}"
      group: "{{ item }}"
      mode: '0755'
    loop: "{{ users }}"

  - name: Get docker group info
    ansible.builtin.getent:
      database: group
      key: docker

  - name: Set Docker GID fact safely
    ansible.builtin.set_fact:
      docker_gid: "{{ ansible_facts.getent_group['docker'][1] }}"

  - name: Create compose.yml
    copy:
      dest: "komodoagent/compose.yml"
      content: |
        services:
          periphery:
            image: ghcr.io/moghtech/komodo-periphery:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
            container_name: komodo-periphery
            labels:
              komodo.skip: ""
              wud.trigger.include: "docker.linkstack"
            restart: unless-stopped
            user: "1000:1000"
            group_add:
              - "{{ docker_gid }}"
            environment:
              HOME: /etc/komodo
              PERIPHERY_ROOT_DIRECTORY: ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}
              PERIPHERY_PASSKEYS: ${PASSKEY}
              PERIPHERY_SSL_ENABLED: "true"
              PERIPHERY_DISABLE_TERMINALS: "false"
              PERIPHERY_INCLUDE_DISK_MOUNTS: "/etc/hostname"
              KOMODO_WEBHOOK_SECRET: "${KOMODO_WEBHOOK_SECRET}"
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock
              - /proc:/proc
              - ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}
            ports:
              - 8120:8120
      owner: "{{ item }}"
      group: "{{ item }}"
      mode: '0644'
    loop: "{{ users }}"

  - name: Run Docker Compose
    community.docker.docker_compose_v2:
      project_src: "komodoagent"
      state: present

  - name: Run setup inside running container
    community.docker.docker_container_exec:
      container: komodo-periphery
      user: root
      argv:
        - sh
        - -c
        - "mkdir -p /etc/komodo && chown -R 1000:1000 /etc/komodo"