services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    mem_limit: 512M

  traccar:
    image: traccar/traccar:latest
    container_name: traccar
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "80:8082"
      - "5000-5150:5000-5150"
      - "5000-5150:5000-5150/udp"
    volumes:
      - ./logs:/opt/traccar/logs:rw
      - ./traccar.xml:/opt/traccar/conf/traccar.xml:ro
      - ./data:/opt/traccar/data:rw
    environment:
      - JAVA_OPTS=-Xms200M -Xmx1g
    mem_limit: 512M
  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: 45876
      KEY: '${VAR_BESZEL_KEY}'
volumes:
  mysql_data:
