---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Developer:
    - Github:
        - icon: github.png
          href: https://github.com/vukilis
    - Website:
        - icon: /icons/logo.png
          href: https://vukilis.com

- Social:
    - Steam:
        - icon: steam.png
          href: https://steamcommunity.com/id/vuk1lis/
    - Instagram:
        - icon: instagram.png
          href: https://www.instagram.com/vukilis97/
    - YouTube:
        - icon: youtube.png
          href: https://youtube.com/vukilis

- Cloud Services:
    - Zoho Mail:
        - icon: si-zoho-#E42527
          href: https://mail.vukilis.com
    - Cloudflare:
        - icon: cloudflare.png
          href: https://dash.cloudflare.com/
    - WakaTime:
        - icon: wakatime.png
          href: https://wakatime.com/
    - Google Analytics:
        - icon: google-analytics.png
          href: https://analytics.google.com/
    - Yandex:
        - icon: yandex.png
          href: https://metrica.yandex.com/
