---
- Networking:
    - Archer C6:
        href: http://192.168.0.1
        icon: avmfritzbox.png
        description: Home Router
        siteMonitor: http://192.168.0.1
    - Huawei:
        href: http://192.168.100.1/
        icon: avmfritzbox.png
        description: ISP Router
        siteMonitor: http://192.168.100.1/

- Infrastructure and Data:
    - Proxmox:
        href: https://192.168.0.200:8006
        icon: proxmox.png
        description: prx-prod
        siteMonitor: https://192.168.0.200:8006
        widget:
            type: proxmox
            url: https://192.168.0.200:8006
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}

- Media & Entertainment:
    - qBittorrent:
        href: http://192.168.0.204
        icon: qbittorrent  #si-qbittorrent
        description: torrent
        siteMonitor: http://192.168.0.204
        widget:
          type: qbittorrent
          url: http://192.168.0.204
          username: {{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}
          password: {{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}
    - Navidrome:
        href: http://192.168.0.205
        icon: navidrome
        description: music server
        siteMonitor: http://192.168.0.205
        widget:
          type: navidrome
          url: http://192.168.0.205
          user: {{HOMEPAGE_VAR_NAVIDROME_USERNAME}}
          token: {{HOMEPAGE_VAR_NAVIDROME_TOKEN}} #md5(password + salt)
          salt: {{HOMEPAGE_VAR_NAVIDROME_SALT}}
- Management:
    - Portainer:
        href: http://192.168.0.51:9000
        icon: portainer.png
        description: portainer
        siteMonitor: http://192.168.0.51:9000
        widget:
            type: portainer
            url: http://192.168.0.51:9000
            env: 2
            key: {{HOMEPAGE_VAR_PORTAINER_KEY}}
    - Dockge:
        href: http://192.168.0.51:9000
        icon: si-docker-#2496ED
        description: dockge

- Monitoring:
    - UptimeKuma:
        href: http://192.168.0.201
        description: uptimekuma
        icon: uptime-kuma.png
        widget:
            type: uptimekuma
            url: http://192.168.0.201
            slug: services
    - Netdata:
        href: http://192.168.0.200:19999
        description: resource monitoring
        icon: netdata.png
        widget:
            type: netdata
            url: http://192.168.0.200:19999

- Security and Identity:
    - AdGuard Home:
        href: http://192.168.0.202
        icon: adguard-home
        description: ad blocking
        siteMonitor: http://192.168.0.202
        widget:
            type: adguard
            url: http://192.168.0.202
            username: {{HOMEPAGE_VAR_ADGUARD_USERNAME}}
            password: {{HOMEPAGE_VAR_ADGUARD_PASSWORD}}
