---
- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: google
    target: _blank

- datetime:
    text_size: xl
    format:
        timeStyle: short
        hourCycle: h23
- openmeteo:
    label: Belgrade
    latitude: 44.804
    longitude: 20.4651
    timezone: Europe/Belgrade
    units: metric
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format:
      maximumFractionDigits: 1
