---
services:
  medusa:
    image: pymedusa/medusa
    container_name: medusa
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade
    volumes:
      - ./data:/config
      - ./downloads:/downloads
      - ./shows:/tv
    ports:
      - 80:80
    restart: unless-stopped
    labels:
      wud.trigger.include: docker.medusa

  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: 45876
      KEY: '${VAR_BESZEL_KEY}'
    labels:
      wud.trigger.include: docker.medusa

  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1
      - IMAGES=1
      - SERVICES=1
      - TASKS=1
      - INFO=1
      - POST=1
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    labels:
      wud.trigger.include: docker.medusa
