services:
  jetlog:
    image: pbogre/jetlog
    environment:
      JETLOG_PORT: 80
      SECRET_KEY: ${VAR_SECRET_KEY}
    volumes:
      - .:/data
    restart: unless-stopped
    ports:
      - 80:80

  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: 45876
      KEY: '${VAR_BESZEL_KEY}'
