---
services:
  medusa:
    image: pymedusa/medusa
    container_name: medusa
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade
    volumes:
      - ./data:/config
      - ./downloads:/downloads
      - ./shows:/tv
    ports:
      - 80:80
    restart: unless-stopped